/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BreadcrumbBar: typeof import('./components/BreadcrumbBar.vue')['default']
    Course: typeof import('./components/Course.vue')['default']
    EventDates: typeof import('./components/EventDates.vue')['default']
    FooterBar: typeof import('./components/FooterBar.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LanguageButton: typeof import('./components/LanguageButton.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    RegisterPopup: typeof import('./components/RegisterPopup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemBar: typeof import('./components/SystemBar.vue')['default']
    ThemeSwitch: typeof import('./components/ThemeSwitch.vue')['default']
  }
}
