/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/about/bugtracker': RouteRecordInfo<'/about/bugtracker', '/about/bugtracker', Record<never, never>, Record<never, never>>,
    '/about/faq': RouteRecordInfo<'/about/faq', '/about/faq', Record<never, never>, Record<never, never>>,
    '/about/login': RouteRecordInfo<'/about/login', '/about/login', Record<never, never>, Record<never, never>>,
    '/about/pochta': RouteRecordInfo<'/about/pochta', '/about/pochta', Record<never, never>, Record<never, never>>,
    '/about/tutorial': RouteRecordInfo<'/about/tutorial', '/about/tutorial', Record<never, never>, Record<never, never>>,
    '/about/vue': RouteRecordInfo<'/about/vue', '/about/vue', Record<never, never>, Record<never, never>>,
    '/about/vuetify': RouteRecordInfo<'/about/vuetify', '/about/vuetify', Record<never, never>, Record<never, never>>,
    '/campus': RouteRecordInfo<'/campus', '/campus', Record<never, never>, Record<never, never>>,
    '/campus/map': RouteRecordInfo<'/campus/map', '/campus/map', Record<never, never>, Record<never, never>>,
    '/study': RouteRecordInfo<'/study', '/study', Record<never, never>, Record<never, never>>,
    '/study/courses': RouteRecordInfo<'/study/courses', '/study/courses', Record<never, never>, Record<never, never>>,
    '/study/courses.[id]': RouteRecordInfo<'/study/courses.[id]', '/study/courses/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/study/timetable': RouteRecordInfo<'/study/timetable', '/study/timetable', Record<never, never>, Record<never, never>>,
  }
}
